### PR TITLE
Path Control

### PR DESCRIPTION
**Pull request by Thomas-dot-G**
#61 fix and null color manage

### CODE REVIEW

**Comment by anqitong** [comment]
You changed ColorSVG to Color RGB

**Comment by Thomas-dot-G** [comment]
Yes because ColorSVG can be used for some other implementations, it's just the rbg thing.
But I can put it back in svg if needed

**Comment by anqitong** [comment]
All right, but I might have conflicts because I'm currently using ColorSVG

**Comment by starsasumi** [comment]
I think it's ok to merge. You could merge this first and I handle the conflicts in awt path.

**Pull request merged**
