### PR TITLE
Drawing & Path fill

### PR DESCRIPTION
**Pull request by Thomas-dot-G**
add xml in Drawing & Path
issue #33

### CODE REVIEW

**Comment by Thomas-dot-G** [comment]
Other shapes can be tested to see if they work (well displayed with the browser)

**Comment by anqitong** [comment]
Why do you need to create colorSVG? The implementation of it is the same as for Color.

**Comment by Thomas-dot-G** [comment]
For the toString, it's better to right the toString once than for every shape where their is a Color.

**Comment by Thomas-dot-G** [comment]
But if we do the model as Xiaxing suggest, it will be changed, but as for now the decision has not yet been done...

**Comment by starsasumi** [comment]
I think we can merge this and refactor it later to be an ShapeState

**Pull request merged**
