### PR TITLE
Modify .gitignore to filter IntelliJ's project files

### PR DESCRIPTION
**Pull request by starsasumi**
#13

### CODE REVIEW

**Comment by Thomas-dot-G** [comment]
Ok, but while you're at it, can you remove:  /Dessin.class

**Comment by starsasumi** [comment]
@Thomas-dot-G That's done! I merge it now.

**Comment by Thomas-dot-G** [comment]
@starsasumi Ok, even if usually, we wait before merging, because in another commit, we can forget something that another can see. (we merge after someone else comment that says, ok, and not after a commit^^)

**Comment by starsasumi** [comment]
Ok, I would not do it again the next time ;P

**Comment by Thomas-dot-G** [comment]
no problem

**Pull request merged**
