### PR TITLE
Shapes Types

### PR DESCRIPTION
**Pull request by Thomas-dot-G**
#23 fix, add class for shapes

### CODE REVIEW

**Comment by anqitong** [comment]
Why do you need pencil here?
public String getXML(Pencil pencil)

Method getColor in ShapesType : maybe it could be coded directly in the interfafce instead of repeating it in each classes (Polygone, .. etc)

And why did you erase the class enum?

**Comment by Thomas-dot-G** [comment]
The class enum has no reason to be there anymore if we code the class directly, no ? (Or what would be the use)
For Pencil, it's because in another PR, a Path is defined by a Shape and a Pencil, or for the XML, we need both, so in Shape, we need the attribute Pencil

**Comment by anqitong** [comment]
I was thinking of simplying the code. For example :
class ShapesType implements ShapesProperties :
private String name; (it could be polygone, line, etc...)

interface ShapesProperties :
getColor, setColor, getXML ..

And afterwards we can create for example a polygone this way :
ShapesType polygone = new ShapesType(ShapesNames.POLYGONE);

**Comment by Thomas-dot-G** [comment]
Ok, I'll do that

**Comment by anqitong** [comment]
I think it is all right

**Comment by starsasumi** [comment]
Why there is some classes in `src/model` and one in `src/Model`?

**Comment by starsasumi** [comment]
I think all classes are ok. And for me concrete shapes and its interface are all model classes. We can just put them together or add prefix `I` to interfaces or add package `model.interface`

**Comment by Thomas-dot-G** [comment]
Not sure what you do mean.
Should I merge or make changes ?
(Please assign someone else once you have commented, thx)

**Comment by Thomas-dot-G** [comment]
Oh yeah, you mean the package specific_shapes in model ?
I meant to do that, but apparently not...

**Comment by starsasumi** [comment]
If you do that on purpose then I am with you 😉. It's OK to merge it. BTW, I can't assign anyone on my phone 😅. I will do that the next time

**Comment by Thomas-dot-G** [comment]
No I meant to put the package Specific_Shapes in the package model
Is that what you meant ?
(I just add a new commit)
(And you just manage to do the assignement^^)

**Comment by starsasumi** [comment]
Yep, I think now it's ok(shapes in model).

I downloaded an app for github, much better!

**Pull request merged**
