### PR TITLE
2_svg (bis)

### PR DESCRIPTION
**Pull request by anqitong**
Deleted 2_svg of my repository.
Repulled from master (so that the project is clean as the beginning).
Created 2_svg (new branch).
Added SvgFile.java and rectified missing blank lines.
#2

### CODE REVIEW

**Comment by starsasumi** [comment]
Should we separate `display(String filename);` method in SvgFile.java into two methods:
- `readSVG(String filename)`
- `display()`

And I think the phrase "SVGFile" could be simplified to "SVG" / "File" in method names.

**Comment by anqitong** [comment]
what should readSVG(String filename) return ? the whole content of the svg file?

**Comment by starsasumi** [comment]
`void` or `boolean`(success or not) I think. Read a SVG is just load the file and it allows users to add shapes to an existed SVG file

**Comment by anqitong** [comment]
If the user wants to add shapes to an existed SVG file, the file must be loaded before shapes are added to it. So for me, the loadging action is included in add(List<Shapes>) for example

**Comment by starsasumi** [comment]
But we don't have any mechanism to load a SVG yet. 

In fact, I don't think we have to add the SVG loading feature. But I do think we don't need the parameter `String filename` in display method. Shouldn't it just display itself?

**Comment by anqitong** [comment]
I don'k know if we'll have to create a type SVGFile with attributes such as : 
- String filename
- String path
- ...

Something like that. If we have an object SVGFile then we don't need String filnename in display

**Comment by starsasumi** [comment]
Yep, I agree with you.

**Comment by Thomas-dot-G** [comment]
If that so, ok (for the changes)

**Comment by anqitong** [comment]
So can I merge now?

**Comment by Thomas-dot-G** [comment]
I thought you would do another commit with the changes suggested (display()...)

**Comment by anqitong** [comment]
But do you also agree with :
"I don'k know if we'll have to create a type SVGFile with attributes such as :

```
String filename
String path
...
```

"

**Comment by Thomas-dot-G** [comment]
Ok for me !

(Even tho you still add something new instead of doing a new PR)
And also, you don't necessarily need to merge with master if there is no conflict, that's the use of the PR.
But that is minor.

**Comment by anqitong** [comment]
Actually I wanted to pull from master in order to update my branch before I push again to 2_svg

**Pull request merged**
