### PR TITLE
SVG example

### PR DESCRIPTION
**Pull request by Thomas-dot-G**
#20 add sag example in a folder

### CODE REVIEW

**Comment by starsasumi** [comment]
@Thomas-dot-G you mean SVG examples? I will start working on it as soon as I come back to Nantes. 😁

**Comment by starsasumi** [comment]
Sorry, never mind. I thought this is an issue assigned to me

**Comment by starsasumi** [comment]
As it is only examples, I think the PR is already okay. Just one small detail, should we need a "docs" folder and put examples for SVG, script and manuals there?

**Comment by anqitong** [comment]
I think it is a good idea to have a folder "ressources", and then creating sub folders like "svg" and "docs" (for documentation)

**Comment by Thomas-dot-G** [comment]
Ok, but once created, please reassign me so I know I have something to change or merge, because I thought no one had answer as the assignment didn't change.

**Comment by Thomas-dot-G** [comment]
So not sure, you want me to rename the folder "file" by "ressources" ?
Because that example is already in a new Folder.

**Comment by anqitong** [comment]
Th name doesn't matter. Name it as you want.

**Comment by Thomas-dot-G** [comment]
So ok ?

**Comment by anqitong** [comment]
Ok

**Pull request merged**
